# Generated by Django 4.1.7 on 2023-03-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('c_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Minorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('c_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=60)),
                ('producto', models.CharField(max_length=120)),
                ('cantidad', models.CharField(max_length=3)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('retiro', models.CharField(max_length=4)),
                ('quien_retira', models.CharField(max_length=60)),
                ('comentarios', models.CharField(max_length=500)),
            ],
        ),
    ]
