# Generated by Django 4.1.7 on 2023-03-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppValfosca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelacion',
            old_name='cambio',
            new_name='desea_cancelar_algun_pedido',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='cancelar_pedido',
            new_name='desea_realizar_algun_cambio',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='fecha_factura',
            new_name='fecha_de_compra_factura',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='nombre_comprador',
            new_name='nombre_y_apellido_del_comprador',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='nro_orden_compra',
            new_name='nro_de_orden_de_compra',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='sucursal',
            new_name='sucursal_donde_realizo_la_compra',
        ),
        migrations.RenameField(
            model_name='minorista',
            old_name='c_postal',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='minorista',
            old_name='fecha_nacimiento',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='metodo_pago',
            new_name='metodo_de_pago',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_comprador',
            new_name='nombre_y_apellido_del_comprador',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='producto',
            new_name='producto_a_comprar',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='retiro',
            new_name='retira_en_sucursal',
        ),
    ]
